"use client";

import { Download } from "lucide-react";
import { Button } from "../ui/button";

const DownloadSummaryButton = ({
  fileName,
  title,
  summaryText,
  createdAt,
}: {
  fileName: string;
  title: string;
  summaryText: string;
  createdAt: string;
}) => {
  const handleDownload = () => {
    const summaryContent = `# ${title}
Generated Summary
Generated On:${new Date(createdAt).toLocaleDateString()}
    
${summaryText}   
Original File: ${fileName}
Generated by Summarizer AI `;

    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-z0-9]/gi, "_")}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };
  return (
    <Button
      className="bg-rose-100 text-rose-600 rounded-full hover:scale-105 transition-all duration-300 hover:bg-rose-50"
      onClick={handleDownload}
    >
      <Download className="h-4 w-4 mr-1" />
      Download Summary
    </Button>
  );
};

export default DownloadSummaryButton;
